security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_DAI, ROLE_DTI, ROLE_ESP]
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
              provider: fos_userbundle
              csrf_token_generator: security.csrf.token_manager

            logout: true
            anonymous: true

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dti/printers/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dai, roles: ROLE_DAI }
        - { path: ^/dti, roles: ROLE_DTI }
        - { path: ^/esp/produtividade/ato, roles: ROLE_ESP }
        - { path: ^/, roles: ROLE_ADMIN }
