security:
    encoders:
        App\Entity\User:
          algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_users:
            entity:
              class: App\Entity\User
              property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~

            # activate different ways to authenticate

            http_basic: false
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            form_login:
              provider: app_users
              check_path: /login_check
              login_path: /login
              post_only: true
              default_target_path: index_geral
            # https://symfony.com/doc/current/security/form_login_setup.html

            #provider: our_db_provider
    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dti/printers/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dai, roles: ROLE_DAI }
        - { path: ^/dti, roles: ROLE_DTI }
        - { path: ^/esp, roles: ROLE_ESP }
        - { path: ^/, roles: ROLE_ADMIN }

        # - { path: ^/editar, roles: ROLE_ADMIN }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }