<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.access_map' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcherInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-foundation/RequestMatcher.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/AccessMapInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/security/Http/AccessMap.php';

$this->services['security.access_map'] = $instance = new \Symfony\Component\Security\Http\AccessMap();

$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/login$'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/register'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/resetting'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dti/printers/status'), array(0 => 'IS_AUTHENTICATED_ANONYMOUSLY'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/home'), array(0 => 'ROLE_CGR', 1 => 'ROLE_DAI', 2 => 'ROLE_DTI', 3 => 'ROLE_ESP', 4 => 'ROLE_CHESP'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/profile'), array(0 => 'ROLE_CGR', 1 => 'ROLE_DAI', 2 => 'ROLE_DTI', 3 => 'ROLE_ESP', 4 => 'ROLE_CHESP'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dai'), array(0 => 'ROLE_DAI'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/dti'), array(0 => 'ROLE_DTI'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/esp/produtividade/ato'), array(0 => 'ROLE_CGR', 1 => 'ROLE_ESP', 2 => 'ROLE_CHESP'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/esp/produtividade/rels'), array(0 => 'ROLE_CGR', 1 => 'ROLE_ESP', 2 => 'ROLE_CHESP'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/lotacao'), array(0 => 'ROLE_CGR', 1 => 'ROLE_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/esp'), array(0 => 'ROLE_CGR', 1 => 'ROLE_ADMIN'), NULL);
$instance->add(new \Symfony\Component\HttpFoundation\RequestMatcher('^/'), array(0 => 'ROLE_ADMIN'), NULL);

return $instance;
