<?php

namespace Proxies\__CG__\App\Entity\dai\rh;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Employee extends \App\Entity\dai\rh\Employee implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'matricula', 'classificacao', 'cargo', 'nome', 'endereco', 'numero', 'bairro', 'cidade', 'uf', 'cep', 'fone', 'email', 'mae', 'pai', 'grauinstrucao', 'especializacoes', 'estadocivil', 'datanascimento', 'naturalidade', 'ufnatu', 'sexo', 'cnh', 'categoria', 'rg', 'orgaoemissor', 'dataemissao', 'ufrg', 'cpf', 'pispasep', 'oab', 'ctps', 'seriectps', 'certmil', 'seriecertmil', 'titulo', 'secao', 'zona', 'ufeleitor', 'banco', 'agencia', 'conta', 'departamento', 'orgao', 'cedido', 'dataposse', 'datatermino', 'files', 'ausencias', 'equipamentos', 'duracao'];
        }

        return ['__isInitialized__', 'matricula', 'classificacao', 'cargo', 'nome', 'endereco', 'numero', 'bairro', 'cidade', 'uf', 'cep', 'fone', 'email', 'mae', 'pai', 'grauinstrucao', 'especializacoes', 'estadocivil', 'datanascimento', 'naturalidade', 'ufnatu', 'sexo', 'cnh', 'categoria', 'rg', 'orgaoemissor', 'dataemissao', 'ufrg', 'cpf', 'pispasep', 'oab', 'ctps', 'seriectps', 'certmil', 'seriecertmil', 'titulo', 'secao', 'zona', 'ufeleitor', 'banco', 'agencia', 'conta', 'departamento', 'orgao', 'cedido', 'dataposse', 'datatermino', 'files', 'ausencias', 'equipamentos', 'duracao'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Employee $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getEventTermino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventTermino', []);

        return parent::getEventTermino();
    }

    /**
     * {@inheritDoc}
     */
    public function getEquipamentos(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEquipamentos', []);

        return parent::getEquipamentos();
    }

    /**
     * {@inheritDoc}
     */
    public function setEquipamentos(\Doctrine\Common\Collections\Collection $equipamentos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEquipamentos', [$equipamentos]);

        return parent::setEquipamentos($equipamentos);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatricula()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMatricula();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatricula', []);

        return parent::getMatricula();
    }

    /**
     * {@inheritDoc}
     */
    public function setMatricula($matricula)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMatricula', [$matricula]);

        return parent::setMatricula($matricula);
    }

    /**
     * {@inheritDoc}
     */
    public function getCargo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCargo', []);

        return parent::getCargo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCargo($cargo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCargo', [$cargo]);

        return parent::setCargo($cargo);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataposse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataposse', []);

        return parent::getDataposse();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataposse($dataposse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataposse', [$dataposse]);

        return parent::setDataposse($dataposse);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatatermino()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatatermino', []);

        return parent::getDatatermino();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatatermino($datatermino)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatatermino', [$datatermino]);

        return parent::setDatatermino($datatermino);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', []);

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', [$nome]);

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', []);

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco($endereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', [$endereco]);

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumero()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumero', []);

        return parent::getNumero();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumero($numero)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumero', [$numero]);

        return parent::setNumero($numero);
    }

    /**
     * {@inheritDoc}
     */
    public function getBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairro', []);

        return parent::getBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function setBairro($bairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairro', [$bairro]);

        return parent::setBairro($bairro);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', []);

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', [$cidade]);

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUf', []);

        return parent::getUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setUf($uf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUf', [$uf]);

        return parent::setUf($uf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', []);

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', [$cep]);

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getFone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFone', []);

        return parent::getFone();
    }

    /**
     * {@inheritDoc}
     */
    public function setFone($fone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFone', [$fone]);

        return parent::setFone($fone);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', []);

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', [$email]);

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function getMae()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMae', []);

        return parent::getMae();
    }

    /**
     * {@inheritDoc}
     */
    public function setMae($mae)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMae', [$mae]);

        return parent::setMae($mae);
    }

    /**
     * {@inheritDoc}
     */
    public function getPai()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPai', []);

        return parent::getPai();
    }

    /**
     * {@inheritDoc}
     */
    public function setPai($pai)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPai', [$pai]);

        return parent::setPai($pai);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrauinstrucao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrauinstrucao', []);

        return parent::getGrauinstrucao();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrauinstrucao($grauinstrucao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrauinstrucao', [$grauinstrucao]);

        return parent::setGrauinstrucao($grauinstrucao);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstadocivil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstadocivil', []);

        return parent::getEstadocivil();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstadocivil($estadocivil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstadocivil', [$estadocivil]);

        return parent::setEstadocivil($estadocivil);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatanascimento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatanascimento', []);

        return parent::getDatanascimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatanascimento($datanascimento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatanascimento', [$datanascimento]);

        return parent::setDatanascimento($datanascimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaturalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaturalidade', []);

        return parent::getNaturalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaturalidade($naturalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaturalidade', [$naturalidade]);

        return parent::setNaturalidade($naturalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getUfnatu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUfnatu', []);

        return parent::getUfnatu();
    }

    /**
     * {@inheritDoc}
     */
    public function setUfnatu($ufnatu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUfnatu', [$ufnatu]);

        return parent::setUfnatu($ufnatu);
    }

    /**
     * {@inheritDoc}
     */
    public function getUfrg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUfrg', []);

        return parent::getUfrg();
    }

    /**
     * {@inheritDoc}
     */
    public function setUfrg($ufrg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUfrg', [$ufrg]);

        return parent::setUfrg($ufrg);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexo', []);

        return parent::getSexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexo($sexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexo', [$sexo]);

        return parent::setSexo($sexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnh', []);

        return parent::getCnh();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnh($cnh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnh', [$cnh]);

        return parent::setCnh($cnh);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategoria', []);

        return parent::getCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategoria($categoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategoria', [$categoria]);

        return parent::setCategoria($categoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getRg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRg', []);

        return parent::getRg();
    }

    /**
     * {@inheritDoc}
     */
    public function setRg($rg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRg', [$rg]);

        return parent::setRg($rg);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgaoemissor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgaoemissor', []);

        return parent::getOrgaoemissor();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgaoemissor($orgaoemissor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgaoemissor', [$orgaoemissor]);

        return parent::setOrgaoemissor($orgaoemissor);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataemissao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataemissao', []);

        return parent::getDataemissao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataemissao($dataemissao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataemissao', [$dataemissao]);

        return parent::setDataemissao($dataemissao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpf()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getCpf();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpf', []);

        return parent::getCpf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpf($cpf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpf', [$cpf]);

        return parent::setCpf($cpf);
    }

    /**
     * {@inheritDoc}
     */
    public function getPispasep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPispasep', []);

        return parent::getPispasep();
    }

    /**
     * {@inheritDoc}
     */
    public function setPispasep($pispasep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPispasep', [$pispasep]);

        return parent::setPispasep($pispasep);
    }

    /**
     * {@inheritDoc}
     */
    public function getOab()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOab', []);

        return parent::getOab();
    }

    /**
     * {@inheritDoc}
     */
    public function setOab($oab)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOab', [$oab]);

        return parent::setOab($oab);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtps', []);

        return parent::getCtps();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtps($ctps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtps', [$ctps]);

        return parent::setCtps($ctps);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriectps()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriectps', []);

        return parent::getSeriectps();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriectps($seriectps)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriectps', [$seriectps]);

        return parent::setSeriectps($seriectps);
    }

    /**
     * {@inheritDoc}
     */
    public function getCertmil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCertmil', []);

        return parent::getCertmil();
    }

    /**
     * {@inheritDoc}
     */
    public function setCertmil($certmil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCertmil', [$certmil]);

        return parent::setCertmil($certmil);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeriecertmil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeriecertmil', []);

        return parent::getSeriecertmil();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeriecertmil($seriecertmil)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeriecertmil', [$seriecertmil]);

        return parent::setSeriecertmil($seriecertmil);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitulo', []);

        return parent::getTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitulo($titulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitulo', [$titulo]);

        return parent::setTitulo($titulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getSecao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSecao', []);

        return parent::getSecao();
    }

    /**
     * {@inheritDoc}
     */
    public function setSecao($secao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSecao', [$secao]);

        return parent::setSecao($secao);
    }

    /**
     * {@inheritDoc}
     */
    public function getZona()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getZona', []);

        return parent::getZona();
    }

    /**
     * {@inheritDoc}
     */
    public function setZona($zona)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setZona', [$zona]);

        return parent::setZona($zona);
    }

    /**
     * {@inheritDoc}
     */
    public function getUfeleitor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUfeleitor', []);

        return parent::getUfeleitor();
    }

    /**
     * {@inheritDoc}
     */
    public function setUfeleitor($ufeleitor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUfeleitor', [$ufeleitor]);

        return parent::setUfeleitor($ufeleitor);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanco', []);

        return parent::getBanco();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanco($banco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanco', [$banco]);

        return parent::setBanco($banco);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgencia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgencia', []);

        return parent::getAgencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgencia($agencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgencia', [$agencia]);

        return parent::setAgencia($agencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getConta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConta', []);

        return parent::getConta();
    }

    /**
     * {@inheritDoc}
     */
    public function setConta($conta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConta', [$conta]);

        return parent::setConta($conta);
    }

    /**
     * {@inheritDoc}
     */
    public function getEspecializacoes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEspecializacoes', []);

        return parent::getEspecializacoes();
    }

    /**
     * {@inheritDoc}
     */
    public function setEspecializacoes($especializacoes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEspecializacoes', [$especializacoes]);

        return parent::setEspecializacoes($especializacoes);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartamento', []);

        return parent::getDepartamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartamento($departamento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartamento', [$departamento]);

        return parent::setDepartamento($departamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassificacao', []);

        return parent::getClassificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassificacao($classificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassificacao', [$classificacao]);

        return parent::setClassificacao($classificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrgao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrgao', []);

        return parent::getOrgao();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrgao($orgao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrgao', [$orgao]);

        return parent::setOrgao($orgao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCedido()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCedido', []);

        return parent::getCedido();
    }

    /**
     * {@inheritDoc}
     */
    public function setCedido($cedido)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCedido', [$cedido]);

        return parent::setCedido($cedido);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', []);

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiles($files)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiles', [$files]);

        return parent::setFiles($files);
    }

    /**
     * {@inheritDoc}
     */
    public function getAusencias(): \Doctrine\Common\Collections\ArrayCollection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAusencias', []);

        return parent::getAusencias();
    }

    /**
     * {@inheritDoc}
     */
    public function setAusencias(\Doctrine\Common\Collections\ArrayCollection $ausencias)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAusencias', [$ausencias]);

        return parent::setAusencias($ausencias);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuracao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuracao', []);

        return parent::getDuracao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuracao($duracao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuracao', [$duracao]);

        return parent::setDuracao($duracao);
    }

}
