<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJanpw7f\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJanpw7f/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJanpw7f.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJanpw7f\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJanpw7f\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Janpw7f',
    'container.build_id' => '637948f3',
    'container.build_time' => 1548206468,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJanpw7f');
