<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCznj5zk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCznj5zk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCznj5zk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCznj5zk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCznj5zk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Cznj5zk',
    'container.build_id' => 'aea70eea',
    'container.build_time' => 1548377098,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCznj5zk');
